const mockedCoursesData = [
  {
    uuid: '1fcffef0-468a-483f-95aa-87e2d4d2c408',
    title: 'Google Cloud Computing Foundations',
    subtitle: 'The Google Cloud Computing Foundations courses provide an overview of concepts central to cloud basics, big data, and machine learning, and where and how Google Cloud fits in.',
    cardImageUrl: 'https://prod-discovery.edx-cdn.org/media/programs/card_images/1fcffef0-468a-483f-95aa-87e2d4d2c408-fc006d5bbc06.png',
    authoringOrganizations: [
      {
        key: 'GoogleCloud',
        logoImageUrl: 'https://prod-discovery.edx-cdn.org/organization/logos/7a30f2c7-0d59-4890-ab19-fc8324e9c7d6-6ff36c37bf48.png',
        name: 'Google Cloud',
      },
    ],
    courses: [
      {
        course: {
          title: 'Google Cloud Computing Foundations: Cloud Computing Fundamentals',
          topics: [],
        },
      },
      {
        course: null,
      },
      {
        course: null,
      },
      {
        course: null,
      },
    ],
    type: 'Professional Certificate',
    marketingPath: '/professional-certificate/google-cloud-computing-foundations',
    organizationLogoOverrideUrl: null,
    organizationShortCodeOverride: '',
    productSource: {
      name: 'edX',
      slug: 'edx',
      description: '',
    },
    status: 'active',
    hidden: false,
    inProspectus: true,
    is2UDegreeProgram: false,
    degree: null,
    locationRestriction: null,
    subscriptionEligible: null,
    objectID: 'program-1fcffef0-468a-483f-95aa-87e2d4d2c408',
    cardType: 'program',
    cardIndex: 0,
  },
  {
    uuid: 'ff89bff4-42c4-4728-ae8b-7e9276ebfcac',
    title: 'Online Master’s Degree in Public Health',
    subtitle: 'from Boston University',
    cardImageUrl: 'https://prod-discovery.edx-cdn.org/media/programs/card_images/ff89bff4-42c4-4728-ae8b-7e9276ebfcac-18ae533b0500.jpeg',
    authoringOrganizations: [
      {
        key: 'BUx',
        logoImageUrl: 'https://prod-discovery.edx-cdn.org/organization/logos/36cfd0bb-1d18-4355-ae44-cb946573df3c-1e18515c3e4b.png',
        name: 'Boston University',
      },
    ],
    courses: [],
    type: 'Masters',
    marketingPath: '/masters/online-masters-in-public-health-boston-university',
    organizationLogoOverrideUrl: null,
    organizationShortCodeOverride: '',
    productSource: {
      name: 'edX',
      slug: 'edx',
      description: '',
    },
    status: 'active',
    hidden: false,
    inProspectus: true,
    is2UDegreeProgram: false,
    degree: {
      quickFacts: [
        {
          text: '$24,000',
          icon: 'fa-dollar',
        },
        {
          text: '6 Modules',
          icon: 'fa-book',
        },
        {
          text: 'Fully Online',
          icon: 'fa-desktop',
        },
        {
          text: '24 Months',
          icon: 'fa-clock-o',
        },
      ],
      additionalMetadata: null,
      organizationLogoOverrideUrl: null,
    },
    locationRestriction: null,
    subscriptionEligible: null,
    objectID: 'program-ff89bff4-42c4-4728-ae8b-7e9276ebfcac',
    cardType: 'program',
    cardIndex: 1,
  },
  {
    uuid: '123f9327-bfef-459f-8bf2-c53277aa58f8',
    title: 'Bachelor of Science in Data Science and Business Analytics',
    subtitle: '',
    cardImageUrl: 'https://prod-discovery.edx-cdn.org/media/programs/card_images/123f9327-bfef-459f-8bf2-c53277aa58f8-60ed48b6667d.png',
    authoringOrganizations: [
      {
        key: 'UniversityofLondon',
        logoImageUrl: 'https://prod-discovery.edx-cdn.org/organization/logos/5427ee88-6dba-46ff-8ed8-87b71e3234da-0af1465ab67e.png',
        name: 'University of London',
      },
    ],
    courses: [],
    type: 'Bachelors',
    marketingPath: '/bachelors/london-bachelor-of-science-in-data-science-and-business-analytics',
    organizationLogoOverrideUrl: null,
    organizationShortCodeOverride: 'University of London',
    productSource: {
      name: '2u',
      slug: '2u',
      description: '2U, Trilogy, Getsmarter -- external source for 2u courses and programs',
    },
    status: 'active',
    hidden: false,
    inProspectus: true,
    is2UDegreeProgram: true,
    degree: {
      quickFacts: [],
      additionalMetadata: {
        externalIdentifier: '2ca2718e-643c-4430-b521-b9ebb91ad226',
        externalUrl: 'https://programs.edx.org/requestinfo/lse?utm_source=edx&utm_medium=referral',
        organicUrl: 'https://programs.edx.org/requestinfo/lse?utm_source=edx&utm_medium=referral',
      },
      organizationLogoOverrideUrl: null,
    },
    locationRestriction: {
      restrictionType: 'blocklist',
      countries: [
        'IN',
      ],
      states: [],
    },
    subscriptionEligible: null,
    objectID: 'program-123f9327-bfef-459f-8bf2-c53277aa58f8',
    cardType: 'program',
    cardIndex: 0,
  },
  {
    uuid: '51037067-2c57-4a58-a963-91918ccee5c8',
    title: 'Leading in a Remote Environment',
    subtitle: 'Remote work presents unique challenges to maintaining relationships and achieving goals. Leaders need to be adaptive in order to mobilize their teams to meet these new challenges.',
    cardImageUrl: 'https://prod-discovery.edx-cdn.org/media/programs/card_images/51037067-2c57-4a58-a963-91918ccee5c8-b24ebade984c.jpeg',
    authoringOrganizations: [
      {
        key: 'HarvardX',
        logoImageUrl: 'https://prod-discovery.edx-cdn.org/organization/logos/44022f13-20df-4666-9111-cede3e5dc5b6-2cc39992c67a.png',
        name: 'Harvard University',
      },
    ],
    courses: [
      {
        course: {
          title: 'Exercising Leadership: Foundational Principles',
          topics: [],
        },
      },
      {
        course: {
          title: 'Remote Work Revolution for Everyone',
          topics: [],
        },
      },
    ],
    type: 'Professional Certificate',
    marketingPath: '/professional-certificate/harvardx-leading-in-a-remote-environment',
    organizationLogoOverrideUrl: null,
    organizationShortCodeOverride: '',
    productSource: {
      name: 'edX',
      slug: 'edx',
      description: '',
    },
    status: 'active',
    hidden: false,
    inProspectus: true,
    is2UDegreeProgram: false,
    degree: null,
    locationRestriction: null,
    subscriptionEligible: true,
    objectID: 'program-51037067-2c57-4a58-a963-91918ccee5c8',
    cardType: 'program',
    cardIndex: 1,
  },
  {
    uuid: '89f39d1a-bb23-4944-b6e0-b51fe25ce932',
    title: 'Master of Science in Artificial Intelligence (MSAI)',
    subtitle: '',
    cardImageUrl: 'https://prod-discovery.edx-cdn.org/media/programs/card_images/89f39d1a-bb23-4944-b6e0-b51fe25ce932-c0b01712082d.jpg',
    authoringOrganizations: [
      {
        key: 'UTAustinX',
        logoImageUrl: 'https://prod-discovery.edx-cdn.org/organization/logos/9d38ad58-87fb-4a89-9f23-c8df318112e3-aec8e9e98a5f.png',
        name: 'The University of Texas at Austin',
      },
    ],
    courses: [],
    type: 'Masters',
    marketingPath: '/masters/online-master-artificial-intelligence-utaustinx',
    organizationLogoOverrideUrl: null,
    organizationShortCodeOverride: '',
    productSource: {
      name: '2u',
      slug: 'emeritus',
      description: '2U, Trilogy, Getsmarter -- external source for 2u courses and programs',
    },
    status: 'active',
    hidden: false,
    inProspectus: true,
    is2UDegreeProgram: true,
    degree: {
      quickFacts: [],
      additionalMetadata: {
        externalIdentifier: '89f39d1a-bb23-4944-b6e0-b51fe25ce932',
        externalUrl: 'https://www.edx.org/masters/online-master-artificial-intelligence-utaustinx',
        organicUrl: 'https://www.edx.org/masters/online-master-artificial-intelligence-utaustinx',
      },
      organizationLogoOverrideUrl: null,
    },
    locationRestriction: null,
    subscriptionEligible: null,
    objectID: 'program-89f39d1a-bb23-4944-b6e0-b51fe25ce932',
    cardType: 'program',
    cardIndex: 0,
  },
];

export default mockedCoursesData;
